const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class PDFGenerator {
  generateReport(analysis, user, outputPath) {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(24).text('TruthLens Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Generated for: ${user.name} (${user.email})`);
      doc.text(`Date: ${new Date().toLocaleString()}`);
      doc.moveDown();

      // Article summary
      doc.fontSize(16).text('Article Summary');
      doc.fontSize(12).text(analysis.summary || analysis.content.substring(0, 500) + '...');
      doc.moveDown();

      // Verdict
      doc.fontSize(16).text('Verdict: ' + analysis.prediction);
      doc.text('Confidence: ' + analysis.confidence + '%');
      doc.moveDown();

      // Reasons
      doc.fontSize(16).text('Reasons:');
      analysis.reasons.forEach((reason, i) => {
        doc.fontSize(12).text(`${i+1}. ${reason}`);
      });
      doc.moveDown();

      // Evidence
      if (analysis.evidence && analysis.evidence.length) {
        doc.fontSize(16).text('Evidence:');
        analysis.evidence.forEach((ev, i) => {
          doc.fontSize(12).text(`${i+1}. ${ev}`);
        });
        doc.moveDown();
      }

      // Footer
      doc.fontSize(10).text('Generated by TruthLens - AI Fake News Detection', { align: 'center' });

      doc.end();
      stream.on('finish', resolve);
      stream.on('error', reject);
    });
  }
}

module.exports = new PDFGenerator();